# Super user permissions are required to use Docker
sudo: required
services:
  - docker
# Run before deploying or before testing
before_install:
  - docker build -f Dockerfile.dev -t andersonpem/docker-vue-test .
# The commands we want to run in the test suite
script:
  - docker run andersonpem/docker-vue-test npm run test:unit

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker Vue"
  env: "DockerVue-env"
  bucket_name: "elasticbeanstalk-us-east-2-032950508404"
  bucket_path: "Docker Vue"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"